name: combinat
description: Simple combinatorics calculator
publish_to: 'none'
version: 1.3.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_math_fork: ^0.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  flutter_launcher_icons: ^0.13.1
  shared_preferences: ^2.2.1

flutter:
  uses-material-design: true

  assets:
    - assets/icon.png

flutter_launcher_icons:
  image_path: "assets/icon.png"
  android: true
  ios: true
  web:
    generate: true
    image_path: "assets/icon.png"
  windows:
    generate: true
    image_path: "assets/icon.png"
  macos:
    generate: true
    image_path: "assets/icon.png"
